version: '3.3'
services:

  korriban_sentinel:
    container_name: korriban_sentinel
    image: harbor.dock1.diff.hu/korriban_sentinel/korriban_sentinel
    ports:
      - 8082:80
    volumes:
      - ./.env:/var/www/.env
      - ./korriban-messenger:/app
      - ./src:/var/www
