version: '3.3'
services:

  korriban_sentinel:
    container_name: korriban_sentinel
    image: harbor.dock1.diff.hu/korriban_sentinel/korriban_sentinel
    volumes:
      - ./.env:/var/www/.env
      - ./.env.messenger:/app/.env
    depends_on:
      - korriban_sentinel-db
    restart: unless-stopped
